=== KrzysztofHerman/IHP-XSD/basicihp.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Component">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Description" type="xs:string" />
              <xs:element name="Netlists">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="NgspiceNetlist">
                      <xs:complexType>
                        <xs:attribute name="value" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Symbols">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Symbol">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="File" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                        <xs:attribute name="type" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Parameters">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Parameter">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Description" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="unit" type="xs:string" use="required" />
                        <xs:attribute name="default_value" type="xs:decimal" use="required" />
                        <xs:attribute name="show" type="xs:boolean" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="schematic_id" type="xs:string" use="required" />
            <xs:attribute name="show_name" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== KrzysztofHerman/IHP-XSD/basicihp.xml
<!-- Add XML Data -->
<Library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="basicihp.xsd" name="IHP=Open-PDK">
    <Component name="sg13_lv_nmos" schematic_id = "M" show_name="true">
        <Description>
            low voltage nmos
        </Description>
        <Netlists>
            <NgspiceNetlist value = 'XM{PartCounter} {nets} sg13_lv_nmos w={w} l={l} ng={ng} m={m}'>
                </NgspiceNetlist>
        </Netlists>
        <Symbols>
            <Symbol id="Standard" type="external"> <!-- Defined in a separate file -->
               <File>{QUCS_S_COMPONENTS_LIBRARY}/Nonlinear_Components_Symbols/NMOS.sym</File>
           </Symbol>
        </Symbols>
        <Parameters>
            <Parameter name="w" unit="um" default_value="1.0" show="true">
                <Description>Width</Description>
            </Parameter>
            <Parameter name="l" unit="um" default_value="0.13" show="true">
                <Description>Length</Description>
            </Parameter>
            <Parameter name="ng" unit="" default_value="1" show="true">
                <Description>Number of fingers</Description>
            </Parameter>
            <Parameter name="m" unit="" default_value="1" show="true">
                <Description>Multiplier</Description>
            </Parameter>
        </Parameters>
    </Component>
</Library>
