=== KrzysztofHerman/IHP-XSD/mos.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Root element -->
    <xs:element name="Library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Component" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Component -->
    <xs:element name="Component">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Description" type="xs:string"/>
                <xs:element name="Models"/>
                <xs:element name="Symbols"/>
                <xs:element name="Parameters"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="schematic_id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Models -->
    <xs:element name="Models">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="DefaultModel"/>
                <xs:element name="SpiceModel"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="DefaultModel">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="SpiceModel">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Symbols -->
    <xs:element name="Symbols">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Symbol"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Symbol">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Line" maxOccurs="unbounded"/>
                <xs:element name="PortSym" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Line">
        <xs:complexType>
            <xs:attribute name="x1" type="xs:int" use="required"/>
            <xs:attribute name="y1" type="xs:int" use="required"/>
            <xs:attribute name="x2" type="xs:int" use="required"/>
            <xs:attribute name="y2" type="xs:int" use="required"/>
            <xs:attribute name="color" type="xs:string" use="required"/>
            <xs:attribute name="width" type="xs:int" use="required"/>
            <xs:attribute name="style" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="PortSym">
        <xs:complexType>
            <xs:attribute name="x" type="xs:int" use="required"/>
            <xs:attribute name="y" type="xs:int" use="required"/>
            <xs:attribute name="type" type="xs:int" use="required"/>
            <xs:attribute name="angle" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Parameters -->
    <xs:element name="Parameters">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Parameter" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Parameter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Description" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="unit" type="xs:string" use="optional"/>
            <xs:attribute name="default_value" type="xs:string" use="required"/>
            <xs:attribute name="show" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== KrzysztofHerman/IHP-XSD/mos.xml
<Library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="mos.xsd" name="IHP=Open-PDK">
    <Component name="sg13_lv_nmos" schematic_id = "M">
        <Description>
            SG13G2 low voltage nmos transistor
        </Description>
        <Models>
                <DefaultModel value = "sg13_lv_nmos">
                </DefaultModel>
                <SpiceModel value = "sg13_lv_nmos">
                </SpiceModel>
        </Models>
        <Symbols>
            <Symbol id="Standard">
                <Line x1="-14" y1="-13" x2="-14" y2="13" color="#000080" width="2" style="1" />
                <Line x1="-30" y1="0" x2="-20" y2="0" color="#000080" width="2" style="1" />
                <Line x1="-20" y1="0" x2="-14" y2="0" color="#000080" width="2" style="1" />
                <Line x1="-10" y1="-11" x2="0" y2="-11" color="#000080" width="2" style="1" />
                <Line x1="0" y1="-11" x2="0" y2="-20" color="#000080" width="2" style="1" />
                <Line x1="0" y1="-20" x2="0" y2="-30" color="#000080" width="2" style="1" />
                <Line x1="-10" y1="11" x2="0" y2="11" color="#000080" width="2" style="1" />
                <Line x1="0" y1="11" x2="0" y2="20" color="#000080" width="2" style="1" />
                <Line x1="0" y1="20" x2="0" y2="30" color="#000080" width="2" style="1" />
                <Line x1="-10" y1="-16" x2="-10" y2="7" color="#000080" width="2" style="1" />
                <Line x1="-10" y1="7" x2="-10" y2="16" color="#000080" width="2" style="1" />
                <Line x1="-10" y1="-8" x2="-10" y2="8" color="#000080" width="2" style="1" />
                <Line x1="-4" y1="24" x2="4" y2="20" color="#000080" width="2" style="1" />
                <Line x1="-8" y1="0" x2="20" y2="0" color="#000080" width="2" style="1" />
                <Line x1="-10" y1="0" x2="-10" y2="0" color="#000080" width="2" style="1" />
                <Line x1="-9" y1="0" x2="-4" y2="-5" color="#000080" width="2" style="1" />
                <Line x1="-9" y1="0" x2="-4" y2="5" color="#000080" width="2" style="1" />
                <PortSym x="0" y="-30" type="1" angle="0" />
                <PortSym x="-30" y="0" type="2" angle="0" />
                <PortSym x="0" y="30" type="3" angle="0"/>
                <PortSym x="20" y="0" type="4" angle="0"/>
            </Symbol>
        </Symbols>
        <Parameters>
            <Parameter name="w" unit="um" default_value="0.5" show="1">
                <Description>Width</Description>
            </Parameter>
            <Parameter name="l" unit="um" default_value="0.5" show="1">
                <Description>Length</Description>
            </Parameter>
            <Parameter name="ng" unit="" default_value="1" show="1">
                <Description>Number of gates</Description>
            </Parameter>
            <Parameter name="m" unit="" default_value="1" show="1">
                <Description>multiplier</Description>
            </Parameter>
        </Parameters>
    </Component>
</Library>
